version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      # Check for maven dependency updates every weekday at 08:00 UTC
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      # Check for updates to container images every weekday at 08:00 UTC
      interval: "weekly"
